# Generated by Django 3.0.4 on 2020-05-13 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApoliceSeguro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=85)),
                ('data_emissao', models.DateField()),
                ('data_validade', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Cbo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoCbo', models.CharField(max_length=85)),
                ('tituloCbo', models.CharField(max_length=85)),
            ],
        ),
        migrations.CreateModel(
            name='Classificacao_tributaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Cnae',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('descricao', models.TextField(default='desc')),
            ],
        ),
        migrations.CreateModel(
            name='CodGps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codGps', models.CharField(max_length=5)),
                ('especificacao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=15)),
                ('logradouro', models.CharField(max_length=45)),
                ('numero', models.CharField(max_length=15)),
                ('complemento', models.CharField(blank=True, max_length=45, null=True)),
                ('bairro', models.CharField(max_length=45)),
                ('cidade', models.CharField(max_length=50)),
                ('pais', models.CharField(max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoCivil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=45)),
                ('name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Natureza_juridica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_categoria', models.CharField(max_length=100)),
                ('cod_subcategoria', models.CharField(max_length=5)),
                ('nome_subcategoria', models.CharField(max_length=150)),
                ('representante_entidade', models.CharField(max_length=150)),
                ('qualificacao', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='OrgaoEmissorDocumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=85)),
                ('name', models.CharField(max_length=85)),
            ],
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=45)),
                ('name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='TipoContrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=85)),
                ('label', models.CharField(max_length=85)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=85)),
                ('name', models.CharField(max_length=85)),
            ],
        ),
        migrations.CreateModel(
            name='TipoSanguineo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(blank=True, max_length=45)),
                ('nome_completo', models.CharField(blank=True, max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Uf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=45)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=85)),
                ('endereco', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gerenciador_de_empresas.Endereco')),
                ('estado_civil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gerenciador_de_empresas.EstadoCivil')),
                ('sexo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gerenciador_de_empresas.Sexo')),
                ('tipo_sanguineo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gerenciador_de_empresas.TipoSanguineo')),
            ],
        ),
        migrations.AddField(
            model_name='endereco',
            name='uf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gerenciador_de_empresas.Uf'),
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apelido', models.CharField(max_length=150, unique=True)),
                ('razao_social', models.CharField(max_length=50)),
                ('nome_fantasia', models.CharField(blank=True, max_length=50, null=True)),
                ('data_abertura', models.DateField(blank=True, null=True)),
                ('telefone_ddd', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=50)),
                ('registro_empregrado', models.BooleanField()),
                ('indicativo_desoneracao', models.BooleanField()),
                ('optante_simples', models.BooleanField()),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('is_instituicao_de_ensino', models.BooleanField(default=0)),
                ('classificacao_tributaria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gerenciador_de_empresas.Classificacao_tributaria')),
                ('cnae_principal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gerenciador_de_empresas.Cnae')),
                ('cod_gps', models.ManyToManyField(blank=True, to='gerenciador_de_empresas.CodGps')),
                ('endereco', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='gerenciador_de_empresas.Endereco')),
                ('naturezas_juridicas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gerenciador_de_empresas.Natureza_juridica')),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(max_length=85, null=True)),
                ('numero', models.CharField(max_length=85, null=True)),
                ('data_emissao', models.CharField(max_length=85, null=True)),
                ('data_vencimento', models.CharField(max_length=85, null=True)),
                ('orgao_emissor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gerenciador_de_empresas.OrgaoEmissorDocumento')),
                ('pessoa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documento', to='gerenciador_de_empresas.Pessoa')),
                ('tipo_doc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gerenciador_de_empresas.TipoDocumento')),
                ('uf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gerenciador_de_empresas.Uf')),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salario', models.CharField(max_length=85)),
                ('data_admissao', models.DateField()),
                ('data_termino_contratual', models.DateField()),
                ('data_termino_efetiva', models.DateField(blank=True, null=True)),
                ('horas_semanais', models.IntegerField(blank=True, null=True)),
                ('horas_mensais', models.IntegerField(blank=True, null=True)),
                ('apolices_seguro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gerenciador_de_empresas.ApoliceSeguro')),
                ('contratado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerenciador_de_empresas.Pessoa')),
                ('contratante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratante', to='gerenciador_de_empresas.Empresa')),
                ('instituicao_de_ensino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gerenciador_de_empresas.Empresa')),
                ('supervisor_estagio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_estagio', to='gerenciador_de_empresas.Pessoa')),
                ('tipo_contrato', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gerenciador_de_empresas.TipoContrato')),
            ],
        ),
        migrations.CreateModel(
            name='CodMunicipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('codigo', models.CharField(max_length=80, unique=True)),
                ('uf', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gerenciador_de_empresas.Uf')),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=85)),
                ('cbo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gerenciador_de_empresas.Cbo')),
            ],
        ),
        migrations.AddField(
            model_name='apoliceseguro',
            name='seguradora',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gerenciador_de_empresas.Empresa'),
        ),
    ]
