# Generated by Django 3.0.4 on 2020-05-13 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador_de_empresas', '0011_empresa_is_instituicao_de_ensino'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='is_instituicao_de_ensino',
        ),
    ]
