# Generated by Django 3.0.4 on 2020-05-13 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador_de_empresas', '0022_contrato_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='cargo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='gerenciador_de_empresas.Cargo'),
        ),
    ]
