# Generated by Django 3.0.4 on 2020-05-13 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador_de_empresas', '0023_auto_20200513_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='cargo',
        ),
    ]
