# Generated by Django 3.0.4 on 2020-05-13 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador_de_empresas', '0025_auto_20200513_1830'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cbo',
            old_name='codigo_cbo',
            new_name='codigoCbo',
        ),
    ]
