# Generated by Django 3.0.4 on 2020-05-13 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador_de_empresas', '0027_contrato_cargo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contrato',
        ),
    ]
