# Generated by Django 3.0.4 on 2020-05-13 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador_de_empresas', '0028_delete_contrato'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salario', models.CharField(max_length=85)),
                ('data_admissao', models.DateField()),
                ('data_termino_contratual', models.DateField()),
                ('data_termino_efetiva', models.DateField(blank=True, null=True)),
                ('horas_semanais', models.IntegerField(blank=True, null=True)),
                ('horas_mensais', models.IntegerField(blank=True, null=True)),
                ('apolices_seguro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gerenciador_de_empresas.ApoliceSeguro')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gerenciador_de_empresas.Cargo')),
                ('contratado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerenciador_de_empresas.Pessoa')),
                ('contratante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratante', to='gerenciador_de_empresas.Empresa')),
                ('instituicao_de_ensino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gerenciador_de_empresas.Empresa')),
                ('supervisor_estagio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_estagio', to='gerenciador_de_empresas.Pessoa')),
                ('tipo_contrato', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gerenciador_de_empresas.TipoContrato')),
            ],
        ),
    ]
