# Generated by Django 3.0.4 on 2020-05-13 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador_de_empresas', '0029_contrato'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contrato',
        ),
    ]
