# Generated by Django 3.0.4 on 2020-05-13 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador_de_empresas', '0031_contrato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargo',
            name='cbo',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='apolices_seguro',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='contratado',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='contratante',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='instituicao_de_ensino',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='supervisor_estagio',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='tipo_contrato',
        ),
        migrations.DeleteModel(
            name='ApoliceSeguro',
        ),
        migrations.DeleteModel(
            name='Cargo',
        ),
        migrations.DeleteModel(
            name='Cbo',
        ),
        migrations.DeleteModel(
            name='Contrato',
        ),
        migrations.DeleteModel(
            name='TipoContrato',
        ),
    ]
