# Generated by Django 3.0.4 on 2020-05-13 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador_de_empresas', '0033_tipocontrato'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApoliceSeguro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=85)),
                ('data_emissao', models.DateField()),
                ('data_validade', models.DateField()),
                ('seguradora', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gerenciador_de_empresas.Empresa')),
            ],
        ),
    ]
