# Generated by Django 3.0.4 on 2020-05-13 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador_de_empresas', '0035_cbo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=85)),
                ('cbo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gerenciador_de_empresas.Cbo')),
            ],
        ),
    ]
