# Generated by Django 3.0.4 on 2020-05-19 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador_de_empresas', '0038_auto_20200519_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipocontrato',
            name='codigo',
            field=models.CharField(default='n/a', max_length=85, unique=True),
        ),
    ]
