# Generated by Django 3.0.4 on 2020-05-19 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador_de_empresas', '0039_auto_20200519_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipocontrato',
            name='codigo',
        ),
    ]
