# Generated by Django 3.0.4 on 2020-05-19 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador_de_empresas', '0040_remove_tipocontrato_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipocontrato',
            name='name',
            field=models.CharField(default=10, max_length=85),
            preserve_default=False,
        ),
    ]
