# Generated by Django 3.0.4 on 2020-05-19 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador_de_empresas', '0042_auto_20200519_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apoliceseguro',
            name='numero',
            field=models.CharField(max_length=85, unique=True),
        ),
    ]
