# Generated by Django 3.0.4 on 2020-05-19 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador_de_empresas', '0060_tipocontrato'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TipoContrato',
        ),
    ]
