# Generated by Django 3.0.4 on 2020-05-19 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador_de_empresas', '0065_tipocontrato_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipocontrato',
            name='name',
        ),
    ]
