# Generated by Django 3.0.4 on 2020-05-19 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador_de_empresas', '0066_remove_tipocontrato_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipocontrato',
            name='name',
            field=models.CharField(default='desc', max_length=85),
            preserve_default=False,
        ),
    ]
