# Generated by Django 3.0.4 on 2020-05-19 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador_de_empresas', '0068_remove_tipocontrato_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipocontrato',
            name='name',
            field=models.CharField(max_length=85, null=True),
        ),
    ]
