# Generated by Django 3.0.4 on 2020-05-19 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador_de_empresas', '0069_tipocontrato_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataPagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pagamento', models.DateField()),
                ('data_inicial_referencia', models.DateField()),
                ('data_final_referencia', models.DateField()),
            ],
        ),
    ]
