# Generated by Django 3.0.4 on 2020-05-19 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador_de_empresas', '0071_periodicidade_proventos_tipoprovento'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='datas_pagamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gerenciador_de_empresas.DataPagamento'),
        ),
    ]
