# Generated by Django 3.0.4 on 2020-05-19 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador_de_empresas', '0073_empresa_numero_matricula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipocontrato',
            name='codigo',
        ),
    ]
