# Generated by Django 3.0.4 on 2020-05-20 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador_de_empresas', '0075_tipocontrato_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='numero_matricula',
        ),
        migrations.AddField(
            model_name='contrato',
            name='numero_matricula',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='proventos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gerenciador_de_empresas.Proventos'),
        ),
    ]
