# Generated by Django 3.0.4 on 2020-05-20 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador_de_empresas', '0076_auto_20200520_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoprovento',
            name='isBaseFgts',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
