# Generated by Django 3.0.4 on 2020-05-20 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador_de_empresas', '0077_tipoprovento_isbasefgts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='datas_pagamento',
        ),
        migrations.AddField(
            model_name='datapagamento',
            name='empresa',
            field=models.ForeignKey(default=30, on_delete=django.db.models.deletion.CASCADE, related_name='datas_pagamento', to='gerenciador_de_empresas.Empresa'),
            preserve_default=False,
        ),
    ]
