# Generated by Django 3.0.4 on 2020-05-20 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador_de_empresas', '0078_auto_20200520_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapagamento',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='datas_pagamento', to='gerenciador_de_empresas.Empresa'),
        ),
    ]
