# Generated by Django 3.0.4 on 2020-05-28 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador_de_empresas', '0080_auto_20200520_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('label', models.CharField(max_length=30)),
                ('numero_do_mes', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('mes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerenciador_de_empresas.Mes')),
            ],
        ),
        migrations.CreateModel(
            name='Calendario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.CharField(max_length=100, unique=True)),
                ('mes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerenciador_de_empresas.Mes')),
            ],
        ),
    ]
