# Generated by Django 3.0.4 on 2020-05-28 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador_de_empresas', '0083_auto_20200528_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mes',
            name='feriados',
        ),
        migrations.AddField(
            model_name='data',
            name='mes',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gerenciador_de_empresas.Mes'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='data',
            name='data',
            field=models.DateField(null=True),
        ),
    ]
