# Generated by Django 3.0.4 on 2020-05-28 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador_de_empresas', '0085_auto_20200528_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='mes',
            name='ano',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gerenciador_de_empresas.Ano'),
            preserve_default=False,
        ),
    ]
