# Generated by Django 3.0.4 on 2020-05-28 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador_de_empresas', '0086_mes_ano'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('label', models.CharField(max_length=35)),
            ],
        ),
        migrations.RemoveField(
            model_name='mes',
            name='ano',
        ),
        migrations.RemoveField(
            model_name='data',
            name='mes',
        ),
        migrations.DeleteModel(
            name='Ano',
        ),
        migrations.DeleteModel(
            name='Mes',
        ),
        migrations.AddField(
            model_name='calendario',
            name='feriado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerenciador_de_empresas.Data'),
        ),
    ]
